name: Neva Trip
develop:
  automake: true
  livereload: true
projects:
  default:
    server:
      env: develop
      host: 'http://localhost'
      static_folder: static
      cache_ttl: 0
      port: 3000
      session_secret: secret
    logs:
      level: silent
    langs: [ ru ]
  nevatrip:
    default:
      api:
        id: secret
        dataset: secret
      sets:
        desktop: [ common, desktop, nevatrip ]
        touch: [ common, touch, nevatrip ]
    ru:
      server:
        port: 3010
    en:
      server:
        port: 3011
    zh:
      server:
        port: 3012
