version: '3.3'

services:
  build:
    image: alpine

  nevatrip:
    image: hello-world
    environment:
      - PROJECT: nevatrip
      - NODE_ENV: develop
    depends_on:
      - build

  moskvatrip:
    image: hello-world
    environment:
      - PROJECT: moskvatrip
      - NODE_ENV: develop
    depends_on:
      - build

  busguide:
    image: hello-world
    environment:
      - PROJECT: busguide
      - NODE_ENV: develop
    depends_on:
      - build

  node:
    build:
      args:
        NODE_ENV: develop
        NODE_VERSION: --lts
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    networks:
      - app-network

  nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - .docker/nginx/conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - node
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email info@nevatrip.ru --agree-tos --no-eff-email --force-renewal -d new.nevatrip.ru

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/deploy/frontend/static/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/deploy/frontend/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge
